"use client";
import { Suspense, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { CheckCircle2, XCircle, Bookmark } from "lucide-react";
import { withinDailyLimit, resolveEntitlements } from "@dibora/core/entitlement";
import { Badge, Button, Card, PageHeader, Progress, inputCls, cx } from "../../../components/ui";
import { QUESTIONS, SUBJECTS, TOPICS, NOTES, topicName, type Question } from "../../../lib/mock";
import { useStore } from "../../../lib/store";
import { topicStats, questionsToday, events } from "../../../lib/analytics";
import { correctText } from "../../../lib/exam";

const shuffle = <T,>(a: T[]) => [...a].sort(() => Math.random() - 0.5);
function Inner() {
  const { state, update, markActive } = useStore(); const sp = useSearchParams(); const u = state.user!;
  const [mode, setMode] = useState(sp.get("mode") ?? "topic"); const [subject, setSubject] = useState("all"); const [topic, setTopic] = useState(sp.get("topic") ?? "all"); const [diff, setDiff] = useState(sp.get("difficulty") ?? "all");
  const [session, setSession] = useState<Question[] | null>(null); const [i, setI] = useState(0); const [sel, setSel] = useState<string | number | null>(null); const [shown, setShown] = useState(false); const [score, setScore] = useState(0);
  const ent = resolveEntitlements(u.plan === "PREMIUM" ? { status: "ACTIVE", endsAt: null, entitlements: { questionsPerDay: 100000, fullQuestionBank: true } } : null);
  const used = questionsToday(state); const allowed = withinDailyLimit(ent, "questionsPerDay", used);
  const wrongIds = useMemo(() => { const last = new Map<string, boolean>(); state.attempts.forEach((a) => a.result.outcomes.forEach((o) => o.status !== "UNANSWERED" && last.set(o.questionId, o.status === "CORRECT"))); state.practice.forEach((p) => last.set(p.qid, p.correct)); return [...last].filter(([, ok]) => !ok).map(([id]) => id); }, [state]);
  const start = () => { let pool = QUESTIONS.filter((q) => u.subjects.includes(q.subjectId));
    if (mode === "wrong") pool = pool.filter((q) => wrongIds.includes(q.id));
    else if (mode === "weak") { const weak = topicStats(state).filter((t) => t.attempted >= 3).sort((a, b) => a.correct / a.attempted - b.correct / b.attempted).slice(0, 2).map((t) => t.topicId); pool = weak.length ? pool.filter((q) => weak.includes(q.topicId)) : pool; }
    else { if (subject !== "all") pool = pool.filter((q) => q.subjectId === subject); if (topic !== "all") pool = pool.filter((q) => q.topicId === topic); }
    if (diff !== "all" && mode !== "wrong") { const d = pool.filter((q) => q.difficulty === diff.toUpperCase()); pool = d.length ? d : pool; }
    pool = shuffle(pool).slice(0, Math.min(15, Math.max(0, 20 - (u.plan === "PREMIUM" ? 0 : used)) || 15)); setSession(pool); setI(0); setSel(null); setShown(false); setScore(0); };
  if (!allowed) return <Card className="text-center"><h1 className="text-xl font-bold">Daily practice limit reached</h1><p className="mt-1 text-sm text-muted">Free accounts can answer 20 questions a day. Come back tomorrow or upgrade for the full question bank.</p><Button href="/pricing" className="mt-4">See Premium</Button></Card>;
  if (!session) return (<><PageHeader title="Practice" sub={`${u.plan === "PREMIUM" ? "Unlimited" : `${Math.max(0, 20 - used)} of 20 free questions left today`}`} />
    <Card className="space-y-4"><div role="radiogroup" aria-label="Practice mode" className="flex flex-wrap gap-2">{[["topic", "By topic"], ["weak", "My weak areas"], ["wrong", `Previously incorrect (${wrongIds.length})`], ["random", "Random"]].map(([k, l]) => <button key={k} role="radio" aria-checked={mode === k} onClick={() => setMode(k!)} className={cx("min-h-[44px] rounded-xl border px-4 text-sm font-medium", mode === k ? "border-primary bg-primary text-white" : "border-border")}>{l}</button>)}</div>
      {(mode === "topic") && <div className="grid gap-3 sm:grid-cols-3"><select aria-label="Subject" className={inputCls} value={subject} onChange={(e) => { setSubject(e.target.value); setTopic("all"); }}><option value="all">All subjects</option>{SUBJECTS.filter((s) => u.subjects.includes(s.id)).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select>
        <select aria-label="Topic" className={inputCls} value={topic} onChange={(e) => setTopic(e.target.value)}><option value="all">All topics</option>{TOPICS.filter((t) => subject === "all" || t.subjectId === subject).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select>
        <select aria-label="Difficulty" className={inputCls} value={diff} onChange={(e) => setDiff(e.target.value)}><option value="all">Any difficulty</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div>}
      <Button onClick={start}>Start practice</Button>{mode === "wrong" && wrongIds.length === 0 && <p className="text-sm text-muted">No incorrect answers yet. Nice work!</p>}</Card></>);
  if (!session.length) return <Card className="text-center"><p className="font-semibold">No questions match those choices.</p><Button className="mt-3" onClick={() => setSession(null)}>Change filters</Button></Card>;
  if (i >= session.length) return <Card className="text-center"><h1 className="text-2xl font-bold">Session complete</h1><p className="mt-2 text-4xl font-extrabold text-primary">{score}/{session.length}</p><div className="mt-4 flex justify-center gap-2"><Button onClick={() => setSession(null)}>Practice again</Button><Button href="/dashboard" variant="secondary">Dashboard</Button></div></Card>;
  const q = session[i]!; const correct = sel != null && (q.type === "NUMERICAL" ? Number(sel) === q.numericAnswer : sel === q.correctOptionId); const note = NOTES.find((n) => n.topicId === q.topicId); const marked = state.bookmarks.some((b) => b.type === "QUESTION" && b.id === q.id);
  const check = () => { if (sel == null || sel === "") return; setShown(true); if (correct) setScore((s) => s + 1); update((s) => ({ ...s, practice: [...s.practice, { qid: q.id, topicId: q.topicId, correct, at: new Date().toISOString() }] })); markActive(); };
  return (<div className="space-y-4"><Progress value={(i / session.length) * 100} label="Session progress" /><p className="text-sm text-muted">Question {i + 1} of {session.length} · {topicName(q.topicId)} · <Badge tone="info">{q.difficulty}</Badge></p>
    <Card><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">{q.text}</h2><button aria-label="Bookmark question" aria-pressed={marked} className="min-h-[44px] min-w-[44px] rounded-xl p-2" onClick={() => update((s) => ({ ...s, bookmarks: marked ? s.bookmarks.filter((b) => !(b.type === "QUESTION" && b.id === q.id)) : [...s.bookmarks, { type: "QUESTION", id: q.id }] }))}><Bookmark size={18} className={marked ? "fill-accent text-accent" : ""} /></button></div>
      {q.type === "NUMERICAL" ? <input aria-label="Your answer" inputMode="decimal" disabled={shown} className={inputCls + " mt-4 text-lg"} value={sel ?? ""} onChange={(e) => setSel(e.target.value)} /> : <fieldset disabled={shown} className="mt-4 space-y-2"><legend className="sr-only">Choices</legend>{q.options.map((o) => <label key={o.id} className={cx("flex min-h-[48px] cursor-pointer items-center gap-3 rounded-xl border p-3", shown && o.id === q.correctOptionId ? "border-success bg-success/10" : shown && sel === o.id ? "border-error bg-error/10" : sel === o.id ? "border-primary bg-primary/10" : "border-border")}><input type="radio" name="a" checked={sel === o.id} onChange={() => setSel(o.id)} />{o.text}</label>)}</fieldset>}</Card>
    {shown && <Card className={correct ? "border-success" : "border-error"}><p className={cx("flex items-center gap-2 font-bold", correct ? "text-success" : "text-error")} role="status">{correct ? <><CheckCircle2 /> Correct! Well done.</> : <><XCircle /> Not quite.</>}</p>{!correct && <p className="mt-1 text-sm">Correct answer: <b>{correctText(q)}</b></p>}<p className="mt-2 text-sm">{q.explanation}</p>
      {!correct && <div className="mt-3 flex flex-wrap gap-2"><Badge>{topicName(q.topicId)}</Badge>{note && <Button href={`/notes/${note.id}`} variant="secondary">Read note</Button>}<Button variant="secondary" onClick={() => { const same = shuffle(QUESTIONS.filter((x) => x.topicId === q.topicId && x.id !== q.id)).slice(0, 5); setSession(same); setI(0); setSel(null); setShown(false); setScore(0); }}>Practice similar</Button></div>}</Card>}
    <div className="flex gap-2">{!shown ? <Button onClick={check} disabled={sel == null || sel === ""}>Check answer</Button> : <Button onClick={() => { setI(i + 1); setSel(null); setShown(false); }}>{i + 1 === session.length ? "Finish" : "Next question"}</Button>}<Button variant="ghost" onClick={() => setSession(null)}>End session</Button></div></div>); }
export default function P() { return <Suspense><Inner /></Suspense>; }
