"use client";
import { useState } from "react";
import { questionUpsertSchema } from "@dibora/validation";
import { Badge, Button, Card, Field, PageHeader, Skeleton, inputCls, useToast } from "../../../components/ui";
import { StatusTable } from "../../../components/StatusTable";
import { useAdmin, type Status } from "../../../lib/admin";
import { SUBJECTS, TOPICS, topicName, type Question } from "../../../lib/mock";
const PLACEHOLDER = "00000000-0000-4000-8000-000000000000"; // demo ids are not UUIDs; the shared rules still validate everything else
const blank = { subjectId: "math", topicId: "alg", difficulty: "EASY", type: "MULTIPLE_CHOICE", text: "", explanation: "", opts: ["", "", "", ""], correct: 0, numeric: "", tolerance: "0" };
export default function P() {
  const { d, set } = useAdmin(); const toast = useToast(); const [f, setF] = useState(blank); const [open, setOpen] = useState(false); const [err, setErr] = useState<string[]>([]); const [preview, setPreview] = useState(false);
  if (!d) return <Skeleton className="h-60" />;
  const parse = () => questionUpsertSchema.safeParse({ subjectId: PLACEHOLDER, topicId: PLACEHOLDER, difficulty: f.difficulty, type: f.type, text: f.text, explanation: f.explanation,
    options: f.type === "NUMERICAL" ? [] : f.type === "TRUE_FALSE" ? [{ text: "True", isCorrect: f.correct === 0 }, { text: "False", isCorrect: f.correct === 1 }] : f.opts.filter((o) => o.trim()).map((t, i) => ({ text: t, isCorrect: i === f.correct })), numericAnswer: f.type === "NUMERICAL" && f.numeric !== "" ? Number(f.numeric) : null, numericTolerance: Number(f.tolerance) || 0 });
  const save = () => { const r = parse(); if (!r.success) { setErr(r.error.issues.map((i) => i.message)); return; } setErr([]); const v = r.data; const id = "q" + Date.now();
    const options = v.options.map((o, i) => ({ id: `${id}-o${i}`, text: o.text })); const ci = v.options.findIndex((o) => o.isCorrect);
    const q: Question & { status: Status } = { id, subjectId: f.subjectId, topicId: f.topicId, difficulty: v.difficulty, type: v.type, text: v.text, options, correctOptionId: ci >= 0 ? options[ci]!.id : undefined, numericAnswer: v.numericAnswer ?? undefined, tolerance: v.numericTolerance, explanation: v.explanation, status: "DRAFT" };
    set((x) => ({ ...x, questions: [q, ...x.questions] }), `Created question ${id}`); toast("Saved as draft"); setF(blank); setOpen(false); setPreview(false); };
  const ch = (ids: string[], s: Status) => { if (s === "PUBLISHED") { const bad = d.questions.filter((q) => ids.includes(q.id) && ((q.type !== "NUMERICAL" && !q.correctOptionId) || !q.explanation)); if (bad.length) return toast("Some questions are incomplete and cannot be published", "error"); } set((x) => ({ ...x, questions: x.questions.map((q) => ids.includes(q.id) ? { ...q, status: s } : q) }), `Set ${ids.length} questions to ${s}`); toast(`${ids.length} → ${s}`); };
  return <><PageHeader title="Question bank" sub={`${d.questions.length} questions`} action={<Button onClick={() => setOpen(!open)}>{open ? "Close editor" : "New question"}</Button>} />
    {open && <Card className="mb-6"><h2 className="font-bold">Question editor</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">
      <Field label="Subject">{(id) => <select id={id} className={inputCls} value={f.subjectId} onChange={(e) => setF({ ...f, subjectId: e.target.value, topicId: TOPICS.find((t) => t.subjectId === e.target.value)?.id ?? "" })}>{SUBJECTS.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select>}</Field>
      <Field label="Topic">{(id) => <select id={id} className={inputCls} value={f.topicId} onChange={(e) => setF({ ...f, topicId: e.target.value })}>{TOPICS.filter((t) => t.subjectId === f.subjectId).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select>}</Field>
      <Field label="Difficulty">{(id) => <select id={id} className={inputCls} value={f.difficulty} onChange={(e) => setF({ ...f, difficulty: e.target.value })}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select>}</Field>
      <Field label="Type">{(id) => <select id={id} className={inputCls} value={f.type} onChange={(e) => setF({ ...f, type: e.target.value })}><option>MULTIPLE_CHOICE</option><option>TRUE_FALSE</option><option>NUMERICAL</option></select>}</Field>
      <div className="sm:col-span-2"><Field label="Question text">{(id) => <textarea id={id} rows={2} className={inputCls} value={f.text} onChange={(e) => setF({ ...f, text: e.target.value })} />}</Field></div>
      {f.type === "MULTIPLE_CHOICE" && f.opts.map((o, i) => <div key={i} className="flex items-center gap-2"><input type="radio" name="correct" aria-label={`Option ${i + 1} is correct`} checked={f.correct === i} onChange={() => setF({ ...f, correct: i })} /><input aria-label={`Option ${i + 1}`} className={inputCls} placeholder={`Option ${i + 1}`} value={o} onChange={(e) => setF({ ...f, opts: f.opts.map((x, j) => j === i ? e.target.value : x) })} /></div>)}
      {f.type === "TRUE_FALSE" && <fieldset className="flex gap-4 sm:col-span-2"><legend className="text-sm font-medium">Correct answer</legend>{["True", "False"].map((l, i) => <label key={l} className="flex items-center gap-2 text-sm"><input type="radio" checked={f.correct === i} onChange={() => setF({ ...f, correct: i })} />{l}</label>)}</fieldset>}
      {f.type === "NUMERICAL" && <><Field label="Correct number">{(id) => <input id={id} inputMode="decimal" className={inputCls} value={f.numeric} onChange={(e) => setF({ ...f, numeric: e.target.value })} />}</Field><Field label="Tolerance (±)">{(id) => <input id={id} inputMode="decimal" className={inputCls} value={f.tolerance} onChange={(e) => setF({ ...f, tolerance: e.target.value })} />}</Field></>}
      <div className="sm:col-span-2"><Field label="Explanation">{(id) => <textarea id={id} rows={2} className={inputCls} value={f.explanation} onChange={(e) => setF({ ...f, explanation: e.target.value })} />}</Field></div></div>
      {err.length > 0 && <ul role="alert" className="mt-3 list-disc pl-5 text-sm text-error">{err.map((e) => <li key={e}>{e}</li>)}</ul>}
      {preview && <div className="mt-3 rounded-xl border border-dashed border-border p-3 text-sm"><p className="font-semibold">{f.text || "(question text)"}</p>{f.type === "NUMERICAL" ? <p className="text-muted">Answer: {f.numeric}</p> : <ul className="mt-1 list-disc pl-5">{(f.type === "TRUE_FALSE" ? ["True", "False"] : f.opts).map((o, i) => <li key={i} className={i === f.correct ? "font-bold text-success" : ""}>{o}</li>)}</ul>}<p className="mt-1 text-muted">{f.explanation}</p></div>}
      <div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => { setPreview(true); const r = parse(); setErr(r.success ? [] : r.error.issues.map((i) => i.message)); }}>Preview & validate</Button><Button onClick={save}>Save draft</Button></div></Card>}
    <StatusTable rows={d.questions} cols={[{ key: "t", label: "Question", render: (r) => <span className="line-clamp-2 max-w-md">{r.text}</span> }, { key: "tp", label: "Topic", render: (r) => topicName(r.topicId) }, { key: "d", label: "Difficulty", render: (r) => <Badge tone="info">{r.difficulty}</Badge> }]} onChange={ch} onDelete={(ids) => set((x) => ({ ...x, questions: x.questions.filter((q) => !ids.includes(q.id)) }), `Deleted ${ids.length} questions`)} /></>; }
